DROP TABLE IF EXISTS department;
-- CREATE TABLE roles (
--   id INTEGER AUTO_INCREMENT PRIMARY KEY,
--   title VARCHAR(50) NOT NULL,

-- )
CREATE TABLE department (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  department_name VARCHAR(50) NOT NULL
)