INSERT INTO departments (department_name)
VALUES 
  ("Human Resources"),
  ("Finance"),
  ("Inorganic"),
  ("Organic"),
  ("Sales"),
  ("Engineering"),
  ("Maintenance"),
  ("Shipping & Recieving");

INSERT INTO roles (title, department_id, salary)
VALUES
  ("Human Resource Manager", 1, 60000),
  ("Human Resource Assistant", 1, 40000),
  ("Finance Manager", 2, 70000),
  ("Finance Assistant", 2, 50000),
  ("Inorganic Production Manager", 3, 80000),
  ("Inorganic Production Team Memeber", 3, 60000),
  ("Organic Production Manager", 4, 80000),
  ("Organic Production Team Member", 4, 60000),
  ("Sales Manager", 5, 60000),
  ("Sales Team Membmer", 5, 40000),
  ("Engineering Manager", 6, 80000),
  ("Engineering Team Memeber", 6, 60000),
  ("Maintenance Manager", 7, 70000),
  ("Maintenance Team Memeber", 7, 50000),
  ("Shipping & Recieving Manager", 8, 60000),
  ("Shipping & Recieving Team Memeber", 8, 40000);

INSERT INTO employees (first_name, last_name, role_id, manager_id)
VALUES 
  ("Theresa", "Morrison", 1, NULL),
  ("Alison", "Welch", 2, 1),
  ("Angela", "Dyer", 2 , 1),
  ("Joanne", "Newman", 3, NULL),
  ("Jonathan", "Allan", 4, 4),
  ("Trevor", "Ince", 5, NULL),
  ("Amy",	"Churchill", 6, 6),
  ("Gavin",	"MacDonald", 6, 6),
  ("Deirdre", "Buckland", 6, 6),
  ("Claire", "Marshall", 6, 6),
  ("Virginia", 'Jones', 7, NULL),
  ("Kevin",	"Ferguson", 8, 11),
  ("Katherine", "North", 8, 11),
  ("Carol",	"Bailey", 8, 11),
  ('Harry',	"Dyer", 8, 11),
  ("Warren", "Turner", 9, NULL),
  ("Amelia", "Nolan", 10, 16),
  ("Gordon", "Turner", 10, 16),
  ("Gabrielle", 'Scott', 10, 16),
  ('Christopher', 'Hamilton', 11, NULL),
  ('Christian',	'Mitchell', 12, 20),
  ('Oliver',	"Allan", 12, 20),
  ('Christian',	'Watson',13 , NULL),
  ('Maria',	'Nolan', 14, 23),
  ('Katherine',	'Mills',14, 23),
  ('Frank',	'Metcalfe', 14, 23),
  ('Harry',	'Lee', 14, 23),
  ('Dorothy',	'Harris', 15, NULL),
  ('Jan',	'Poole', 16, 28),
  ('Ian',	'Smith', 16, 28);